/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BenefitItem {
  'id' : bigint,
  'title' : string,
  'evidenceLevel' : EvidenceLevel,
  'sourceCitation' : string,
  'description' : string,
}
export type EvidenceLevel = { 'strong' : null } |
  { 'preliminary' : null } |
  { 'moderate' : null };
export interface FaqEntry {
  'id' : bigint,
  'question' : string,
  'answer' : string,
  'category' : string,
}
export interface PricingEntry {
  'id' : bigint,
  'monthlyEstimate' : string,
  'priceRangePerLb' : string,
  'pricePerServing' : string,
  'productType' : string,
  'notes' : string,
}
export interface ProteinCalculationResult {
  'fitnessGoal' : string,
  'dailyProteinTargetG' : number,
  'bodyWeightKg' : number,
  'servingsPerDay' : bigint,
  'dosePerServingG' : number,
}
export interface SafetyItem {
  'id' : bigint,
  'title' : string,
  'detail' : string,
  'category' : string,
  'severity' : SeverityLevel,
}
export type SeverityLevel = { 'mild' : null } |
  { 'severe' : null } |
  { 'moderate' : null };
export interface WheyType {
  'id' : string,
  'name' : string,
  'fatContent' : string,
  'proteinPercent' : bigint,
  'description' : string,
  'bestFor' : Array<string>,
  'lactoseContent' : string,
  'costRangePerLb' : string,
}
export interface _SERVICE {
  'calculateProtein' : ActorMethod<[number, string], ProteinCalculationResult>,
  'getBenefits' : ActorMethod<[], Array<BenefitItem>>,
  'getFaqs' : ActorMethod<[], Array<FaqEntry>>,
  'getPricingData' : ActorMethod<[], Array<PricingEntry>>,
  'getSafetyInfo' : ActorMethod<[], Array<SafetyItem>>,
  'getWheyTypes' : ActorMethod<[], Array<WheyType>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];