/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProteinCalculationResult = IDL.Record({
  'fitnessGoal' : IDL.Text,
  'dailyProteinTargetG' : IDL.Float64,
  'bodyWeightKg' : IDL.Float64,
  'servingsPerDay' : IDL.Nat,
  'dosePerServingG' : IDL.Float64,
});
export const EvidenceLevel = IDL.Variant({
  'strong' : IDL.Null,
  'preliminary' : IDL.Null,
  'moderate' : IDL.Null,
});
export const BenefitItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'evidenceLevel' : EvidenceLevel,
  'sourceCitation' : IDL.Text,
  'description' : IDL.Text,
});
export const FaqEntry = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const PricingEntry = IDL.Record({
  'id' : IDL.Nat,
  'monthlyEstimate' : IDL.Text,
  'priceRangePerLb' : IDL.Text,
  'pricePerServing' : IDL.Text,
  'productType' : IDL.Text,
  'notes' : IDL.Text,
});
export const SeverityLevel = IDL.Variant({
  'mild' : IDL.Null,
  'severe' : IDL.Null,
  'moderate' : IDL.Null,
});
export const SafetyItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'detail' : IDL.Text,
  'category' : IDL.Text,
  'severity' : SeverityLevel,
});
export const WheyType = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'fatContent' : IDL.Text,
  'proteinPercent' : IDL.Nat,
  'description' : IDL.Text,
  'bestFor' : IDL.Vec(IDL.Text),
  'lactoseContent' : IDL.Text,
  'costRangePerLb' : IDL.Text,
});

export const idlService = IDL.Service({
  'calculateProtein' : IDL.Func(
      [IDL.Float64, IDL.Text],
      [ProteinCalculationResult],
      ['query'],
    ),
  'getBenefits' : IDL.Func([], [IDL.Vec(BenefitItem)], ['query']),
  'getFaqs' : IDL.Func([], [IDL.Vec(FaqEntry)], ['query']),
  'getPricingData' : IDL.Func([], [IDL.Vec(PricingEntry)], ['query']),
  'getSafetyInfo' : IDL.Func([], [IDL.Vec(SafetyItem)], ['query']),
  'getWheyTypes' : IDL.Func([], [IDL.Vec(WheyType)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProteinCalculationResult = IDL.Record({
    'fitnessGoal' : IDL.Text,
    'dailyProteinTargetG' : IDL.Float64,
    'bodyWeightKg' : IDL.Float64,
    'servingsPerDay' : IDL.Nat,
    'dosePerServingG' : IDL.Float64,
  });
  const EvidenceLevel = IDL.Variant({
    'strong' : IDL.Null,
    'preliminary' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const BenefitItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'evidenceLevel' : EvidenceLevel,
    'sourceCitation' : IDL.Text,
    'description' : IDL.Text,
  });
  const FaqEntry = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const PricingEntry = IDL.Record({
    'id' : IDL.Nat,
    'monthlyEstimate' : IDL.Text,
    'priceRangePerLb' : IDL.Text,
    'pricePerServing' : IDL.Text,
    'productType' : IDL.Text,
    'notes' : IDL.Text,
  });
  const SeverityLevel = IDL.Variant({
    'mild' : IDL.Null,
    'severe' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const SafetyItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'detail' : IDL.Text,
    'category' : IDL.Text,
    'severity' : SeverityLevel,
  });
  const WheyType = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'fatContent' : IDL.Text,
    'proteinPercent' : IDL.Nat,
    'description' : IDL.Text,
    'bestFor' : IDL.Vec(IDL.Text),
    'lactoseContent' : IDL.Text,
    'costRangePerLb' : IDL.Text,
  });
  
  return IDL.Service({
    'calculateProtein' : IDL.Func(
        [IDL.Float64, IDL.Text],
        [ProteinCalculationResult],
        ['query'],
      ),
    'getBenefits' : IDL.Func([], [IDL.Vec(BenefitItem)], ['query']),
    'getFaqs' : IDL.Func([], [IDL.Vec(FaqEntry)], ['query']),
    'getPricingData' : IDL.Func([], [IDL.Vec(PricingEntry)], ['query']),
    'getSafetyInfo' : IDL.Func([], [IDL.Vec(SafetyItem)], ['query']),
    'getWheyTypes' : IDL.Func([], [IDL.Vec(WheyType)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };