/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SafetyItem {
    id: bigint;
    title: string;
    detail: string;
    category: string;
    severity: SeverityLevel;
}
export interface FaqEntry {
    id: bigint;
    question: string;
    answer: string;
    category: string;
}
export interface WheyType {
    id: string;
    name: string;
    fatContent: string;
    proteinPercent: bigint;
    description: string;
    bestFor: Array<string>;
    lactoseContent: string;
    costRangePerLb: string;
}
export interface PricingEntry {
    id: bigint;
    monthlyEstimate: string;
    priceRangePerLb: string;
    pricePerServing: string;
    productType: string;
    notes: string;
}
export interface BenefitItem {
    id: bigint;
    title: string;
    evidenceLevel: EvidenceLevel;
    sourceCitation: string;
    description: string;
}
export interface ProteinCalculationResult {
    fitnessGoal: string;
    dailyProteinTargetG: number;
    bodyWeightKg: number;
    servingsPerDay: bigint;
    dosePerServingG: number;
}
export enum EvidenceLevel {
    strong = "strong",
    preliminary = "preliminary",
    moderate = "moderate"
}
export enum SeverityLevel {
    mild = "mild",
    severe = "severe",
    moderate = "moderate"
}
export interface backendInterface {
    calculateProtein(bodyWeightKg: number, fitnessGoal: string): Promise<ProteinCalculationResult>;
    getBenefits(): Promise<Array<BenefitItem>>;
    getFaqs(): Promise<Array<FaqEntry>>;
    getPricingData(): Promise<Array<PricingEntry>>;
    getSafetyInfo(): Promise<Array<SafetyItem>>;
    getWheyTypes(): Promise<Array<WheyType>>;
}
import type { BenefitItem as _BenefitItem, EvidenceLevel as _EvidenceLevel, SafetyItem as _SafetyItem, SeverityLevel as _SeverityLevel } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateProtein(arg0: number, arg1: string): Promise<ProteinCalculationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateProtein(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateProtein(arg0, arg1);
            return result;
        }
    }
    async getBenefits(): Promise<Array<BenefitItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBenefits();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBenefits();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFaqs(): Promise<Array<FaqEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFaqs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFaqs();
            return result;
        }
    }
    async getPricingData(): Promise<Array<PricingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricingData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricingData();
            return result;
        }
    }
    async getSafetyInfo(): Promise<Array<SafetyItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafetyInfo();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafetyInfo();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWheyTypes(): Promise<Array<WheyType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWheyTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWheyTypes();
            return result;
        }
    }
}
function from_candid_BenefitItem_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BenefitItem): BenefitItem {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_EvidenceLevel_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvidenceLevel): EvidenceLevel {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SafetyItem_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SafetyItem): SafetyItem {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SeverityLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeverityLevel): SeverityLevel {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    evidenceLevel: _EvidenceLevel;
    sourceCitation: string;
    description: string;
}): {
    id: bigint;
    title: string;
    evidenceLevel: EvidenceLevel;
    sourceCitation: string;
    description: string;
} {
    return {
        id: value.id,
        title: value.title,
        evidenceLevel: from_candid_EvidenceLevel_n4(_uploadFile, _downloadFile, value.evidenceLevel),
        sourceCitation: value.sourceCitation,
        description: value.description
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    detail: string;
    category: string;
    severity: _SeverityLevel;
}): {
    id: bigint;
    title: string;
    detail: string;
    category: string;
    severity: SeverityLevel;
} {
    return {
        id: value.id,
        title: value.title,
        detail: value.detail,
        category: value.category,
        severity: from_candid_SeverityLevel_n9(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mild: null;
} | {
    severe: null;
} | {
    moderate: null;
}): SeverityLevel {
    return "mild" in value ? SeverityLevel.mild : "severe" in value ? SeverityLevel.severe : "moderate" in value ? SeverityLevel.moderate : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    strong: null;
} | {
    preliminary: null;
} | {
    moderate: null;
}): EvidenceLevel {
    return "strong" in value ? EvidenceLevel.strong : "preliminary" in value ? EvidenceLevel.preliminary : "moderate" in value ? EvidenceLevel.moderate : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BenefitItem>): Array<BenefitItem> {
    return value.map((x)=>from_candid_BenefitItem_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SafetyItem>): Array<SafetyItem> {
    return value.map((x)=>from_candid_SafetyItem_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
